package ch09test

import ch09.{SubsetsCombinatorialGenerator, SubsetsGenerator}
import org.scalatest.{FunSpec, Inside, Matchers}


/**
  * 9.4 Test
  */
class SubsetsGeneratorTest extends FunSpec with Matchers with Inside {


  describe("generated subsets functionally") {
    it("should equal subsets generated by the combinatorial algorithm") {
      for (
        set <- List(List(1,2,3),List(1,2,3,4,5,6))
      ) {
        val listFun = SubsetsGenerator.generateSubsets(set)
        val listComb = SubsetsCombinatorialGenerator.generateSubsets(set)
        assert(listComb.toSet == listFun.toSet)
      }
    }
  }

}
